stages:
  train_model:
    cmd: python3 train.py
    deps:
      - train.py
    outs:
      - models/model.pkl
  test_model:
    cmd: python3 test.py
    deps:
      - test.py
      - models/model.pkl
    metrics:
      - metrics.json